#!/usr/bin/env python3
"""Export the published cards as CSV, JSON, and BibTeX.

A paper atlas is expected to be reusable outside its own website: a reader should be
able to load the collection into a spreadsheet, a script, or a reference manager. The
three files are derived from `library/`, so they carry exactly the cards the site
publishes.

Outputs (generated, safe to delete):

    exports/papers.csv
    exports/papers.json
    exports/papers.bib
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import re
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas import config
from atlas.cards import load_cards, load_tracks

ROOT = config.ROOT

CSV_COLUMNS = [
    "entry_id", "title", "year", "venue", "authors", "tracks", "priority",
    "source_role", "verification_contract", "supervision_granularity",
    "training_use", "construction_layer", "domains", "tags",
    "one_line_summary", "one_line_summary_zh", "primary_link", "code", "data",
    "huggingface", "project",
]

# BibTeX needs plain ASCII-ish keys and escaped braces in titles.
BIB_KEY_NOISE = re.compile(r"[^a-z0-9]+")
BIB_ESCAPE = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_"}


def joined(values) -> str:
    """Some cards carry a numeric tag, so every list item is coerced before joining."""
    return "; ".join(str(v) for v in (values or []))


def artifact(entry: dict, key: str) -> str:
    for link in entry.get("links") or []:
        if link["key"] == key:
            return link["url"]
    return ""


def bib_key(entry: dict) -> str:
    author = (entry["authors"][0].split()[-1].lower() if entry.get("authors") else "anon")
    slug = BIB_KEY_NOISE.sub("", str(entry["title"] or "").lower())[:18]
    return f"{BIB_KEY_NOISE.sub('', author)}{entry.get('year') or 'nd'}{slug}"


def bib_escape(text: str) -> str:
    out = str(text or "")
    for char, replacement in BIB_ESCAPE.items():
        out = out.replace(char, replacement)
    return out


def as_csv(entries: list) -> str:
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=CSV_COLUMNS, lineterminator="\n")
    writer.writeheader()
    for entry in entries:
        writer.writerow({
            "entry_id": entry["id"],
            "title": entry["title"],
            "year": entry.get("year") or "",
            "venue": entry.get("venue") or "",
            "authors": joined(entry.get("authors")),
            "tracks": joined(entry["tracks"]),
            "priority": entry.get("priority") or "",
            "source_role": joined(entry["source_role"]),
            "verification_contract": joined(entry["verification_contract"]),
            "supervision_granularity": joined(entry["supervision_granularity"]),
            "training_use": joined(entry["training_use"]),
            "construction_layer": joined(entry["construction_layer"]),
            "domains": joined(entry["domains"]),
            "tags": joined(entry["tags"]),
            "one_line_summary": entry["one_line"][0],
            "one_line_summary_zh": entry["one_line"][1],
            "primary_link": entry.get("primary_link") or "",
            "code": artifact(entry, "code"),
            "data": artifact(entry, "data"),
            "huggingface": artifact(entry, "huggingface"),
            "project": artifact(entry, "project"),
        })
    return buffer.getvalue()


def as_json(entries: list) -> str:
    payload = [
        {
            "entry_id": entry["id"],
            "title": entry["title"],
            "year": entry.get("year"),
            "venue": entry.get("venue"),
            "authors": entry.get("authors") or [],
            "tracks": entry["tracks"],
            "priority": entry.get("priority") or "",
            "facets": {
                key: entry[key]
                for key in ("source_role", "verification_contract",
                            "supervision_granularity", "training_use", "construction_layer")
            },
            "domains": entry["domains"],
            "tags": entry["tags"],
            "one_line_summary": {"en": entry["one_line"][0], "zh": entry["one_line"][1]},
            "primary_link": entry.get("primary_link"),
            "artifacts": {link["key"]: link["url"] for link in entry.get("links") or []},
            "card": f"{config.REPO_URL}/tree/main/library/cards/{entry['id']}",
        }
        for entry in entries
    ]
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def as_bibtex(entries: list) -> str:
    lines = [
        "% Published cards from the Awesome LLM Reasoning Data atlas.",
        "% Generated by scripts/render_exports.py from library/. Do not edit by hand.",
        "",
    ]
    seen = {}
    for entry in entries:
        key = bib_key(entry)
        seen[key] = seen.get(key, 0) + 1
        if seen[key] > 1:
            key = f"{key}{seen[key]}"
        fields = [
            ("title", bib_escape(entry["title"])),
            ("author", bib_escape(" and ".join(entry.get("authors") or []))),
            ("year", entry.get("year") or ""),
            ("journal", bib_escape(entry.get("venue") or "")),
            ("url", entry.get("primary_link") or ""),
            ("note", bib_escape(entry["one_line"][0])),
        ]
        lines.append(f"@article{{{key},")
        lines += [f"  {name} = {{{value}}}," for name, value in fields if value]
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def build(target: Path) -> int:
    entries, _details, _rows, _dropped = load_cards(config.show_detail_blocks())
    load_tracks()
    exports = target / "exports"
    exports.mkdir(parents=True, exist_ok=True)
    (exports / "papers.csv").write_text(as_csv(entries), encoding="utf-8")
    (exports / "papers.json").write_text(as_json(entries), encoding="utf-8")
    (exports / "papers.bib").write_text(as_bibtex(entries), encoding="utf-8")
    return len(entries)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the exports are stale")
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            temp = Path(tmp)
            build(temp)
            problems = []
            for path in sorted((temp / "exports").iterdir()):
                actual = ROOT / "exports" / path.name
                if not actual.exists():
                    problems.append(f"missing exports/{path.name}")
                elif actual.read_text(encoding="utf-8") != path.read_text(encoding="utf-8"):
                    problems.append(f"out of date: exports/{path.name}")
            for problem in problems:
                print("ERROR:", problem)
            if problems:
                print("Run: python scripts/render_exports.py")
                return 1
        print("exports are up to date")
        return 0

    count = build(ROOT)
    print(f"exported {count} published cards to exports/papers.csv, papers.json, papers.bib")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
